### ISSUE TITLE
sorun ne

### ISSUE THREAD

**Issue by Crisleay** [x000001x/e-forcer#5]
![resim_2023-05-26_124913438](https://github.com/x000001x/e-forcer/assets/108397614/09ec8c20-a4d6-4471-89f7-8da592718b7c)
sanırım bir şeyi yanlış yapıyorum

**Comment by x000001x** [comment]
> 
> ![resim_2023-05-26_124913438](https://github.com/x000001x/e-forcer/assets/108397614/09ec8c20-a4d6-4471-89f7-8da592718b7c)
> sanırım bir şeyi yanlış yapıyorum

Bu hata geneldr Python veya Pip paket yoneticisi indirilmedigine olusur.
