### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Crisleay** [x000001x/e-forcer#7]
![resim_2023-05-26_204027775](https://github.com/x000001x/e-forcer/assets/108397614/f4b7f5c7-8e5b-45ee-b59e-a21dc8c4d6e0)
helpp

**Comment by x000001x** [comment]
> ![resim_2023-05-26_204027775](https://user-images.githubusercontent.com/108397614/241287411-f4b7f5c7-8e5b-45ee-b59e-a21dc8c4d6e0.png) helpp

https://github.com/x000001x/e-forcer/issues/3
