### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Crisleay** [x000001x/e-forcer#8]
![resim_2023-05-26_221719322](https://github.com/x000001x/e-forcer/assets/108397614/fa8f5746-a540-425a-81ad-425f16cb0443)
her şeyi denedim

**Comment by x000001x** [comment]
FFmpeg'i indirdinizmi? [Issue 6](https://github.com/x000001x/e-forcer/issues/6)

**Comment by Crisleay** [comment]
Evet

**Comment by x000001x** [comment]
Indirdiginiz FFmpeg'in icindeki **bin** klasorunun icindekileri programdaki **ffmpeg** adli klasore aktarmalisiniz.
